# Generated by Django 3.2 on 2023-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nongovernmentorg',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
