<<<<<<< HEAD
# Generated by Django 3.2 on 2023-02-18 20:27
=======
# Generated by Django 3.2 on 2023-02-18 23:58
>>>>>>> 765766c277bd3a3b283ce81c36c41aa4f5632997

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGOBlog', '0002_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/featured_image'),
        ),
    ]
